#+TITLE: Workshop: HTTP Prompt

* Intro

** Who are you?

Hi, I'm wade.

- 5+ years at Twilio
  + Software engineer on various Platform Engineering teams
- Passionate builder and teacher
  + I love enabling developers to do cool things with our platform
  + Looking to focus my carreer more directly on education
- Collector of hobbies
  + Board gaming
  + Bicycling
  + Beer brewing
  + Hang gliding
  + Knitting
  + Sewing
  + Meat smoking
  + Language learning
  + Tech tinkering

** What is the HTTP Prompt thing?

*HTTP Prompt is an interactive terminal application for issuing hand-crafted HTTP requests.*

I like to think of it as a simplified, terminal-based friend of Postman (or, a more personable relative of curl!).

Its delicious syntax is based on HTTPie, a popular, and more cleverly named Python library.

** Okay, but Why?

It offers exquisite creature comforts for shell-dwellers!

HTTP is a textual protocol. Some find it more natural to interact with it through a text-first interface, rather than via a GUI.

While there are some other terminal-based HTTP clients, HTTP Prompt is in a league of its own. The key differentiator, as you'll see, is that HTTP Prompt is both *interactive* and *contextual*. These attributes lead to useful features, and a marked improvement in overall usability and ergonomics.

** How might it be useful to me?

HTTP Prompt can be your friend any time you find yourself:

- Exploring a new API
- Troubleshooting problems with your own API
- Running ad-hoc API requests as part of day-to-day testing, debugging, or analysis tasks

Basically any time you want to set up a "tinkering workflow" involving permutations of API requests, HTTP Prompt can help.

** What it's not for

HTTP Prompt is an excellent interface for an inquisitive *human*. It is not designed for programmatic consumption.

- Scripting
- Collaboration

* Installation and basic usage

** Installation

HTTP Prompt is a Python application with only a few simple dependencies. The latest version only supports Python 3, so if you're on an older Python version, be sure to install the *1.0.0* version of the package for Python 2 compatibility.

*** Checking which Python version you have

If you're not sure which Python version you have installed, run this command to find out:

#+BEGIN_SRC shell
> python --version
#+END_SRC shell

*** For Python 2

#+BEGIN_SRC shell
> pip install http-prompt==1.0.0
#+END_SRC

*** For Python 3

#+BEGIN_SRC shell
> pip install http-prompt
#+END_SRC

*** If all else fails

Yout can ssh into my ec2 instance and use the pre-installed version there. :)

#+BEGIN_SRC shell
ssh guest-x@backup.junkyard.digital -p 2222
#+END_SRC

Ask me for a username and password.

*** Time check - target 5 minutes

** Basic usage

Note: for illustration purposes, we'll be making requests against httpbin. This excellent API basically just echoes back whatever requests we send it, which is perfect for testing out a client.

http://httpbin.org/#/Anything

*** Request syntax

Start the app by running the http-prompt command, with a base URL as an argument. Now you can make requests by specifying just the relative path, which will be appended to the base URL:

#+BEGIN_SRC http-prompt
> http-prompt https://httpbin.org

get /anything        # <--- issues a GET request to https://httpbin.org/anything

get /anything/else   # <--- issues a GET request to https://httpbin.org/anything/else
#+END_SRC

We can make a POST request, like this:

#+BEGIN_SRC http-prompt
post /anything     # <--- issues a POST request to https://httpbin.org/anything
#+END_SRC

Cool.

As you see, to make a request using a given HTTP method, you just use the appropriate method/verb (e.g. "get") followed by a URL or path.

There you have it - this is the core functionality of the utility. But it isn't much use without being able to include _data_ with our requests. Let's check it out.

*** Request headers (and introducing session context)

_Please put away for terminal for the time being. We'll need it again later!_

To send an HTTP header with a request, you simply add the header name and value -- separated by a colon -- to your command, like so:

#+BEGIN_SRC http-prompt
get /anything Authorization:secret-api-key
#+END_SRC

Many APIs will require such an auth header to be sent with *every* request, and I don't want to have to type it every time. HTTP Prompt offers an intuitive affordance for such cases in its /session context/ mechanism.

Session context is a way to store data which will be sent with every request.

If you specify a header name and value -- *without actually issuing a request command along with it* -- then the header will be saved in the HTTP Prompt session's context, and the header will be automatically sent along with every subsequent request:

#+BEGIN_SRC http-prompt
Authorization:secret-api-key # <--- save the header in the context

env                          # <--- show the current context

get /anything                # <--- this request will include the Authorization header
get /anything/else           # <--- this request will, too
#+END_SRC

When you don't want the header to be sent anymore, you can remove it from the context as follows:

#+BEGIN_SRC http-prompt
rm -h Authorization     # <--- remove the Authorization header from the context

env                     # <--- show the current context

get /anything           # <--- this request will not include the Authorization header
#+END_SRC

*** Quick recap

So far we've just learned the two most important ergonomic concepts of HTTP Prompt:

1. Easily specifying HTTP request data, such as headers
2. Saving request parameters into the context to have them applied to all future requests

Make sure you are comfortable with these concepts before we proceed.

Next, I'll show you how these two features apply to other types of request data, and then introduce some other neat tricks.

*** Time check - target 10 minutes

* Feature presentation
** Query parameters

Sending a query parameter with a request works the same was as sending a header, only with slightly variation in how the key value pair are expressed. We use a double equal sign ("==") to separate the key/value pair, rather than a colon (":").

Here's an example of specifying a query parameter with a request:

#+BEGIN_SRC http-prompt
get /anything q==dumplings
#+END_SRC

Specifying multiple paramaters works just like you'd expect:

#+BEGIN_SRC http-prompt
get /anything q==dumplings page_size==100 order_by==filling
#+END_SRC

As with headers, whenever you want to send the same query parameter with repeated requests, you can save parameters in the session context. They will then be automatically included with each subsequent request:

#+BEGIN_SRC http-prompt
page_size==100                    # <--- save page_size parameter to context
order_by==filling                 # <--- save order_by parameter to context

get /anything q==dumplings        # <--- this request will include all 3 parameters
get /anything q=="hot pockets"    # <--- this request, too
#+END_SRC

Unsurprisingly, you can always delete unwanted parameters from the session context:

#+BEGIN_SRC http-prompt
rm -q order_by

get /anything q==meatballs        # <--- this request will not include the order_by parameter
#+END_SRC

** Post payloads

HTTP Prompt assumes that you're talking to a server that speaks JSON.

When sending a POST request with data, it automatically:

- Adds a Content-Type header of "application/json"
- Encodes the data as a JSON object.

This turns out to be quite convenient in most cases, since modern web APIs tend to speak JSON.

#+BEGIN_SRC http-prompt
post /anything order=xiaolongbao filling=pork
#+END_SRC

By default, all values, even numbers will be encoded as JSON string values. For example, the following sends the count value as "12".

#+BEGIN_SRC http-prompt
post /anything order=xiaolongbao filling=pork count=12
#+END_SRC

This isn't always what you want - some APIs require JSON values other than strings.

Thus, a convenient syntax is provided for sending "raw" JSON data, including numeric, boolean, or list values, for example:

#+BEGIN_SRC http-prompt
post /anything order=xiaolongbao filling:=pork count:=12
#+END_SRC

Note that this time, the count value was sent as an integer type.

More types:

#+BEGIN_SRC http-prompt
post /anything order=xiaolongbao filling:=["pork","shrimp"] count:=12 chili_oil:=true
#+END_SRC

Finally, just like with headers and query parameters, payload data items may be stored in session context to be sent automatically:

#+BEGIN_SRC http-prompt
order=xiaolongbao
count:=12
chili_oil:=true

post /anything filling=pork     # <--- request includes order, count, chili_oil data
post /anything filling=shrimp   # <--- request includes order, count, chili_oil data
#+END_SRC

** Getting help

At any time in the prompt you can enter the "help" command, for a list of available commands and options.

There are also the following resources for further information or assistance:

- The documentation
- The Discord channel

** Time check - target 15 minutes

** More UX goodness

*** History buffer

Hit the up arrow (or CTRL-U) to rifle through your previous command history.

*** Autocomplete

HTTP Prompt predicts likely values for certain types of commands and arguments. When an auto-complete menu is displayed, hit <TAB> (or CTRL-N) to cycle through the options until you reach the one you like. After selecting a desired value from the auto-complete menu, just continue typing the rest of your command, or hit <Enter> to issue the command.

Some auto-complete menus to check out:

- Options for request verbs, e.g. get or post shows auto-complete suggestions for options such as --auth
- Common header names and values, e.g. Content-Type, shows auto-complete suggestions for common mime types
- Previously executed commands from the session history
- API endpoints from an OpenAPI spec

*** Contextual requests

You've already seen how HTTP Prompt allows you to issue commands using relative URL paths, when a base URL is set. Now we'll take that further, by changing the context's base URL with the cd command.

http://httpbin.org/#/Status_codes

#+BEGIN_SRC http-prompt
cd status # < --- changes context's base url to https://httpbin.org/status

get 404   # < --- issues a request to https://httpbin.org/status/404

cd 500    # < --- changes context's base url to https://httpbin.org/status/500

get       # < --- issues a request to https://httpbin.org/status/500

cd ../302 # < --- changes context's base url back to https://httpbin.org/302

get       # < --- issues a request to https://httpbin.org/status/302
#+END_SRC

You can also use cd to change the entire base URL, including the hostname.

#+BEGIN_SRC http-prompt
cd https://api.funtranslations.com/translate

get doge.json text==helloworld

cd https://www.affirmations.dev

get
#+END_SRC

*** Command pipelines

Oftentimes, especially with larger response bodies, you'll need to filter the content of a response, and/or pass the response body to another application fur further processing. Just like with Unix pipelines, this can be can accomplished in HTTP Prompt by "piping" the output to an external application of your choosing.

I've found that the most useful examples typically involve filtering the response to find target elements, for example using jq or grep.

Multiple commands can be combined to further refine the output:

#+BEGIN_SRC http-prompt
cd https://pokeapi.co/api/v2

limit==100

get pokemon | jq | grep -C2 caterpie

get pokemon/10

get pokemon/10 | jq .moves[].move.name | sort
#+END_SRC

*** Save and load sessions

Finally, one of my favorite features is a simple one: the HTTP Prompt session context, including not only base URL but also any set headers, query params, authorization options, etc, can be saved to disk and reloaded at another time.

This allows you to save a session context for each particular API you tend to work with, and then later you can quickly pick up session for any API without needing to again set up the URL, path, authentication, etc... I'll demonstrate this feature in a moment.

*** Time check - target 20 minutes. Whew.

* Putting it all together

** A final recap

The main topics we've learned about:

- Making requests with data
  + Headers
  + Query parameters
  + JSON payloads
- Saving things in the session context for re-use
  + Base URL and path
  + Request data to be included with all requests
- Filtering response data by piping it to shell programs
- Using command history and auto-complete

There are a slew of other features that I'm leaving out, for brevity, but these are the ones I mostly use.

Now I'll briefly show you a couple of examples where I use these features for interacting with a real-world APIs.

** Demo 1: GitHub

https://docs.github.com/en/rest/reference/repos#list-repositories-for-the-authenticated-user

https://docs.github.com/en/rest/reference/pulls#create-a-pull-request

#+BEGIN_SRC http-prompt
source github

get users/onlywade/repos sort==updated | jq .[].name

cd repos/onlywade/.doom.d

get pulls/1

post pulls head=dired_emacs_mode base=main title="Alawys launch dired in emacs mode"
#+END_SRC

** Demo 2: Ravelry

https://www.ravelry.com/api#projects_list

#+BEGIN_SRC http-prompt
source ravelry

get projects/onlywade/list.json

get <img_url> --download
#+END_SRC

** Time check - target 25 minutes

* Break for questions

* Practice time!

** Capture the flag

This type of activity is an infosec tradition designed to exercise cybersecurity and problem-solving skills. The objective is to complete a series of tasks (usually of increasing difficulty), eventually leading to acquisition of a password, file, or other piece of protected information (i.e. the "flag").

In this case I've tailored the tasks to focus on API exploration in order to exercise human-driven HTTP client usage.

Also, the target challenge level is LOW. But watch out! The flag is protected by a guard dog.

Start by approaching the creature with a GET request to https://junkyard.digital/doggo.

*** Quick reference

**** Project docs

https://docs.http-prompt.com

**** Getting started on capture the flag

Remember you can change the base URL/path with "cd" and then make relative requests:

#+BEGIN_SRC http-prompt
cd https://junkyard.digital.com

get /doggo
#+END_SRC

**** Specifying request data

***** Headers

#+BEGIN_SRC http-prompt
get /path key:value      # <--- send header with a single request
key:value                # <--- save header in context to send with all #+END_SRC

***** Query parameters

#+BEGIN_SRC http-prompt
key==value               # <--- send param with a single request
get /path key==value     # <--- save param in context to send with all
get /path key=="a b c"   # <--- use quotes for specifying strings with spaces
#+END_SRC

***** JSON payloads

#+BEGIN_SRC http-prompt
post /path key=value     # <--- send payload value as string
post /path key:=value    # <--- send payload value as raw JSON type
#+END_SRC

**** Request options

***** Basic Auth

#+BEGIN_SRC http-prompt
--auth username:password # <--- send basic auth credentials with request
#+END_SRC

***** File download for binary content

#+BEGIN_SRC http-prompt
--download               # <--- download the response content as a file
#+END_SRC

* Wrapping up

** Limitations & contra-indications

To be honest -- *most* of the times when I find myself needing to fire off a one-off API request or two, I reach for curl. Part of this is perhaps just muscle memory, but there are also reasons to prefer curl over HTTP Prompt in some situations:

- curl is available everywhere, and is probably already installed
  + even in a remote server environment, for example
- curl is pretty much universally understood
- curl is usually more appropriate for use in a programmatic or scripting context

I should also note that HTTP Prompt is not without its limitations:

- It doesn't have affordances for response assertions or tests
- Isn't great for crafting large, multi-line payloads
- Doesn't have first-class collaboration features
- It isn't under very active development, has some bugs and unfinished features

In general, though, any time there's an API endpoint you just want to poke around at for a while, give HTTP Prompt a shot! You might love it.

** Safety measures

*** Clear history

By default - and like many other terminal-based applications - HTTP Prompt stores recent session context and history in files within your home directory. Because it's likely that your HTTP Prompt session commands include API tokens or other secrets, you may want to delete these files when finished, or configure HTTP Prompt to avoid storing them altogether.

To delete the files on Mac OS, you can run the following command:

#+BEGIN_SRC sh
rm ~/.local/share/http-prompt/*
#+END_SRC

To find out how to disable persistent history completely, check the manual.

** Further reading, next steps

*** Try it out the next time you need to twiddle an API

*** Check out the project page, documentation, and source code

*** Learn about the underlying client library, HTTPie

https://httpie.io/

*** Hack on the project!

**** Add support for curl format
**** Fix bugs
** Q&A
